# Generated by Django 5.2.17 on 2026-09-01 22:26

import django.db.models.deletion
import django.utils.timezone
import synthesis.managers
import synthesis.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('gestor', 'Gestor'), ('gerente', 'Gerente'), ('admin', 'Administrador técnico')], default='gestor', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='synthesis.area')),
            ],
            options={
                'ordering': ('name', 'email'),
            },
            managers=[
                ('objects', synthesis.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('result', models.TextField()),
                ('beneficiaries', models.CharField(max_length=240)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_reports', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_reports', to='synthesis.area')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='activities/%Y/%m/', validators=[synthesis.validators.validate_image_size, synthesis.validators.validate_image_content_type])),
                ('name', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('activity_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='synthesis.activityreport')),
            ],
            options={
                'ordering': ('-is_main', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_sections', to='synthesis.area')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editorial_title', models.CharField(max_length=200)),
                ('editorial_summary', models.TextField()),
                ('editorial_result', models.TextField()),
                ('original_date', models.DateField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('removed', models.BooleanField(default=False)),
                ('activity_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='synthesis.activityreport')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='synthesis.area')),
                ('selected_photo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='synthesis.activityphoto')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='synthesis.reportsection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WeeklyCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada'), ('reaberta', 'Reaberta')], default='aberta', max_length=16)),
                ('reopen_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-starts_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at'))), name='cycle_dates_valid')],
            },
        ),
        migrations.AddField(
            model_name='activityreport',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_reports', to='synthesis.weeklycycle'),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('em_selecao', 'Em seleção'), ('rascunho', 'Rascunho'), ('em_edicao', 'Em edição'), ('pdf_gerado', 'PDF gerado')], default='rascunho', max_length=20)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_report', to='synthesis.weeklycycle')),
                ('selected_activities', models.ManyToManyField(blank=True, related_name='weekly_reports', to='synthesis.activityreport')),
            ],
            options={
                'ordering': ('-cycle__starts_at',),
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(upload_to='reports/%Y/%m/')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_report_versions', to=settings.AUTH_USER_MODEL)),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='synthesis.weeklyreport')),
            ],
            options={
                'ordering': ('version',),
            },
        ),
        migrations.AddField(
            model_name='reportsection',
            name='weekly_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='synthesis.weeklyreport'),
        ),
        migrations.AddConstraint(
            model_name='activityphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('activity_report',), name='one_main_photo_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('section', 'activity_report'), name='one_activity_per_section'),
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.UniqueConstraint(fields=('weekly_report', 'version'), name='unique_report_version'),
        ),
        migrations.AddConstraint(
            model_name='reportsection',
            constraint=models.UniqueConstraint(fields=('weekly_report', 'area'), name='one_section_per_area_report'),
        ),
    ]
