# Generated by Django 5.2.17 on 2026-09-03 00:12

import django.db.models.functions.text
from django.db import migrations, models


def fill_blank_user_names(apps, schema_editor):
    user_model = apps.get_model("synthesis", "User")
    for user in user_model.objects.filter(name="").only("id", "email").iterator():
        local_part = user.email.partition("@")[0].replace(".", " ").replace("_", " ").strip()
        user.name = (local_part.title() or "Usuário")[:150]
        user.save(update_fields=("name",))


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('synthesis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_blank_user_names, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='activityphoto',
            index=models.Index(fields=['activity_report', '-is_main'], name='photo_activity_main_idx'),
        ),
        migrations.AddIndex(
            model_name='activityreport',
            index=models.Index(fields=['cycle', '-date', '-created_at'], name='activity_cycle_date_idx'),
        ),
        migrations.AddIndex(
            model_name='activityreport',
            index=models.Index(fields=['manager', 'cycle'], name='activity_manager_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='activityreport',
            index=models.Index(fields=['area', 'cycle'], name='activity_area_cycle_idx'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['active', 'order'], name='area_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity', 'entity_id'], name='audit_entity_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', '-created_at'], name='audit_actor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-created_at'], name='audit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['section', 'removed', 'order'], name='card_section_state_order_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['weekly_report', 'order'], name='section_report_order_idx'),
        ),
        migrations.AddIndex(
            model_name='reportversion',
            index=models.Index(fields=['weekly_report', '-generated_at'], name='version_report_date_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'active'], name='user_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklycycle',
            index=models.Index(fields=['status', '-starts_at'], name='cycle_status_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityreport',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='activity_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='activityreport',
            constraint=models.CheckConstraint(condition=models.Q(('location', ''), _negated=True), name='activity_location_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='activityreport',
            constraint=models.CheckConstraint(condition=models.Q(('summary', ''), _negated=True), name='activity_summary_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='activityreport',
            constraint=models.CheckConstraint(condition=models.Q(('result', ''), _negated=True), name='activity_result_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='activityreport',
            constraint=models.CheckConstraint(condition=models.Q(('beneficiaries', ''), _negated=True), name='activity_beneficiaries_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='area_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='area_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('action', ''), _negated=True), name='audit_action_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('entity', ''), _negated=True), name='audit_entity_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('entity_id', ''), _negated=True), name='audit_entity_id_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.CheckConstraint(condition=models.Q(('editorial_title', ''), _negated=True), name='card_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.CheckConstraint(condition=models.Q(('editorial_summary', ''), _negated=True), name='card_summary_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.CheckConstraint(condition=models.Q(('editorial_result', ''), _negated=True), name='card_result_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='report_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='user_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['gestor', 'gerente', 'admin'])), name='user_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'gestor'), _negated=True), ('area__isnull', False), _connector='OR'), name='manager_requires_area'),
        ),
        migrations.AddConstraint(
            model_name='weeklycycle',
            constraint=models.CheckConstraint(condition=models.Q(('label', ''), _negated=True), name='cycle_label_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='weeklycycle',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['aberta', 'encerrada', 'reaberta'])), name='cycle_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='weeklycycle',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'reaberta'), _negated=True), models.Q(('reopen_reason', ''), _negated=True), _connector='OR'), name='reopened_cycle_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='weeklyreport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['nao_iniciado', 'em_selecao', 'rascunho', 'em_edicao', 'pdf_gerado'])), name='report_status_valid'),
        ),
    ]
