# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations, models


def copy_card_metadata(apps, schema_editor):
    card_model = apps.get_model("synthesis", "ReportCard")
    for card in card_model.objects.select_related("activity_report__manager").iterator():
        activity = card.activity_report
        card.original_location = activity.location
        card.original_beneficiaries = activity.beneficiaries
        card.original_manager_name = activity.manager.name
        card.save(
            update_fields=("original_location", "original_beneficiaries", "original_manager_name")
        )


class Migration(migrations.Migration):
    dependencies = [
        ("synthesis", "0002_harden_postgres_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="original_location",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reportcard",
            name="original_beneficiaries",
            field=models.CharField(default="", max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reportcard",
            name="original_manager_name",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.RunPython(copy_card_metadata, migrations.RunPython.noop),
    ]
