# Generated by Django 5.2.17 on 2026-09-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesis', '0003_reportcard_snapshot_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateWindow',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='session_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='content_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='is_normalized',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
